import type { NovatedLeaseFormState } from "@/lib/calculators/novatedLease";

export type FieldUnit =
  | "AUD"
  | "AUD/year"
  | "AUD/month"
  | "%"
  | "days"
  | "months"
  | "date"
  | "none";

export type FieldMeta = {
  label: string;
  description: string;
  unit: FieldUnit;
  formatRule: string;
  validationMessage: string;
  defaultValue: string;
  modes: Array<"quote" | "detailed" | "both">;
};

export const novatedLeaseFieldMeta: Record<keyof NovatedLeaseFormState, FieldMeta> = {
  s: {
    label: "Gross Annual Salary",
    description: "Your pre-package salary before deductions.",
    unit: "AUD/year",
    formatRule: "Number >= 0",
    validationMessage: "Enter salary greater than 0.",
    defaultValue: "120000",
    modes: ["both"],
  },
  pf: {
    label: "Pay Frequency",
    description: "How often you are paid.",
    unit: "none",
    formatRule: "One of weekly, fortnightly, monthly",
    validationMessage: "Select a pay frequency.",
    defaultValue: "fortnightly",
    modes: ["both"],
  },
  fy: {
    label: "Income Tax Year",
    description: "Tax bracket table version used for estimates.",
    unit: "none",
    formatRule: "One of supported financial years",
    validationMessage: "Select a valid tax year.",
    defaultValue: "FY2025-26",
    modes: ["both"],
  },
  ml: {
    label: "Include Medicare Levy",
    description: "Apply base Medicare levy estimate.",
    unit: "none",
    formatRule: "Boolean",
    validationMessage: "Select Medicare levy preference.",
    defaultValue: "true",
    modes: ["both"],
  },
  mlr: {
    label: "Medicare Levy Override",
    description: "Optional decimal override (e.g. 0.02).",
    unit: "%",
    formatRule: "Optional number >= 0",
    validationMessage: "Must be a non-negative number.",
    defaultValue: "empty",
    modes: ["detailed"],
  },
  fyd: {
    label: "FBT Year Days",
    description: "Total days in FBT year.",
    unit: "days",
    formatRule: "365 or 366",
    validationMessage: "Enter 365 or 366.",
    defaultValue: "365",
    modes: ["detailed"],
  },
  dav: {
    label: "Days Available for Private Use",
    description: "Days vehicle was available in FBT year.",
    unit: "days",
    formatRule: "0 to FBT year days",
    validationMessage: "Must be between 0 and FBT year days.",
    defaultValue: "365",
    modes: ["detailed"],
  },
  fsr: {
    label: "FBT Statutory Rate Override",
    description: "Optional decimal (0 to 1).",
    unit: "%",
    formatRule: "Optional number in range 0..1",
    validationMessage: "Must be between 0 and 1.",
    defaultValue: "empty",
    modes: ["detailed"],
  },
  vt: {
    label: "Vehicle Type",
    description: "Fuel/technology category of the vehicle.",
    unit: "none",
    formatRule: "Petrol/Diesel, Hybrid, Plug-in Hybrid, Electric vehicle, Hydrogen",
    validationMessage: "Select a vehicle type.",
    defaultValue: "Electric vehicle",
    modes: ["both"],
  },
  pp: {
    label: "Vehicle Purchase Price (incl. GST)",
    description: "Drive-away estimate including GST.",
    unit: "AUD",
    formatRule: "Number >= 0",
    validationMessage: "Enter a non-negative purchase price.",
    defaultValue: "50000",
    modes: ["both"],
  },
  bv: {
    label: "FBT Base Value (optional)",
    description: "Optional override for FBT base value.",
    unit: "AUD",
    formatRule: "Optional number >= 0",
    validationMessage: "Must be a non-negative number.",
    defaultValue: "empty",
    modes: ["detailed"],
  },
  eve: {
    label: "Vehicle Eligible for EV FBT Exemption",
    description: "Set true only if eligibility conditions are met.",
    unit: "none",
    formatRule: "Boolean",
    validationMessage: "Set eligibility status.",
    defaultValue: "auto",
    modes: ["detailed"],
  },
  fhud: {
    label: "First Held and Used Date (optional)",
    description: "Used for transitional EV/PHEV checks.",
    unit: "date",
    formatRule: "YYYY-MM-DD",
    validationMessage: "Enter a valid date.",
    defaultValue: "empty",
    modes: ["detailed"],
  },
  phex: {
    label: "PHEV Exempt Before 1 Apr 2025",
    description: "Transitional condition for PHEV.",
    unit: "none",
    formatRule: "Boolean",
    validationMessage: "Set true/false.",
    defaultValue: "false",
    modes: ["detailed"],
  },
  phbc: {
    label: "Binding Commitment Before 1 Apr 2025",
    description: "Second transitional condition for PHEV.",
    unit: "none",
    formatRule: "Boolean",
    validationMessage: "Set true/false.",
    defaultValue: "false",
    modes: ["detailed"],
  },
  tm: {
    label: "Lease Term",
    description: "Contract length in months.",
    unit: "months",
    formatRule: "12, 24, 36, 48, or 60",
    validationMessage: "Choose a supported term.",
    defaultValue: "36",
    modes: ["both"],
  },
  ir: {
    label: "Interest Rate",
    description: "Nominal annual rate used for lease estimate.",
    unit: "%",
    formatRule: "Number >= 0",
    validationMessage: "Enter a non-negative interest rate.",
    defaultValue: "8.5",
    modes: ["detailed"],
  },
  ppy: {
    label: "Payments Per Year",
    description: "Finance payment frequency used in repayment model.",
    unit: "none",
    formatRule: "12, 26, or 52",
    validationMessage: "Select 12, 26, or 52.",
    defaultValue: "12",
    modes: ["detailed"],
  },
  ef: {
    label: "Establishment Fee",
    description: "Upfront fee included in financed amount in this model.",
    unit: "AUD",
    formatRule: "Number >= 0",
    validationMessage: "Enter a non-negative fee.",
    defaultValue: "500",
    modes: ["detailed"],
  },
  maf: {
    label: "Monthly Account Keeping Fee",
    description: "Recurring lease administration fee.",
    unit: "AUD/month",
    formatRule: "Number >= 0",
    validationMessage: "Enter a non-negative monthly fee.",
    defaultValue: "15",
    modes: ["detailed"],
  },
  rvo: {
    label: "Residual Value Override (optional)",
    description: "Optional balloon amount override (must pass minimum checks).",
    unit: "AUD",
    formatRule: "Optional number >= minimum residual and < purchase price",
    validationMessage: "Must satisfy residual constraints.",
    defaultValue: "empty",
    modes: ["detailed"],
  },
  rr: {
    label: "Registration",
    description: "Annual registration cost.",
    unit: "AUD/year",
    formatRule: "Number >= 0",
    validationMessage: "Enter non-negative annual registration.",
    defaultValue: "900",
    modes: ["detailed"],
  },
  ri: {
    label: "Insurance",
    description: "Annual insurance cost.",
    unit: "AUD/year",
    formatRule: "Number >= 0",
    validationMessage: "Enter non-negative annual insurance.",
    defaultValue: "1400",
    modes: ["detailed"],
  },
  rm: {
    label: "Maintenance",
    description: "Annual servicing/maintenance estimate.",
    unit: "AUD/year",
    formatRule: "Number >= 0",
    validationMessage: "Enter non-negative annual maintenance.",
    defaultValue: "800",
    modes: ["detailed"],
  },
  rt: {
    label: "Tyres",
    description: "Annual tyre budget.",
    unit: "AUD/year",
    formatRule: "Number >= 0",
    validationMessage: "Enter non-negative annual tyres.",
    defaultValue: "300",
    modes: ["detailed"],
  },
  rf: {
    label: "Fuel or Electricity",
    description: "Annual energy/fuel spend.",
    unit: "AUD/year",
    formatRule: "Number >= 0",
    validationMessage: "Enter non-negative annual fuel/electricity.",
    defaultValue: "2200",
    modes: ["detailed"],
  },
  ro: {
    label: "Other Eligible Car Expenses",
    description: "Other annual eligible costs in package.",
    unit: "AUD/year",
    formatRule: "Number >= 0",
    validationMessage: "Enter non-negative annual other costs.",
    defaultValue: "200",
    modes: ["detailed"],
  },
  ue: {
    label: "Use ECM",
    description: "Apply Employee Contribution Method to reduce FBT taxable value.",
    unit: "none",
    formatRule: "Boolean",
    validationMessage: "Set true/false.",
    defaultValue: "true",
    modes: ["detailed"],
  },
  evt: {
    label: "Apply EV FBT Exemption Toggle",
    description: "Apply EV exemption only if eligibility conditions are true.",
    unit: "none",
    formatRule: "Boolean",
    validationMessage: "Set true/false.",
    defaultValue: "auto",
    modes: ["detailed"],
  },
  irc: {
    label: "Include Running Costs in Package",
    description: "Whether annual running costs are packaged with lease.",
    unit: "none",
    formatRule: "Boolean",
    validationMessage: "Set true/false.",
    defaultValue: "true",
    modes: ["both"],
  },
  qn: {
    label: "Quote Provider Name",
    description: "Optional provider reference for quote-first analysis.",
    unit: "none",
    formatRule: "Text",
    validationMessage: "Optional text.",
    defaultValue: "empty",
    modes: ["quote"],
  },
  qpp: {
    label: "Quoted Per-Pay Deduction",
    description: "Total deduction quoted per pay cycle.",
    unit: "AUD",
    formatRule: "Optional number >= 0",
    validationMessage: "Must be non-negative.",
    defaultValue: "empty",
    modes: ["quote"],
  },
  qad: {
    label: "Quoted Annual Deduction",
    description: "Total quoted annual deduction.",
    unit: "AUD",
    formatRule: "Optional number >= 0",
    validationMessage: "Must be non-negative.",
    defaultValue: "empty",
    modes: ["quote"],
  },
  qrv: {
    label: "Quoted Residual Value",
    description: "Residual value shown in quote, if provided.",
    unit: "AUD",
    formatRule: "Optional number >= 0",
    validationMessage: "Must be non-negative.",
    defaultValue: "empty",
    modes: ["quote"],
  },
  qrp: {
    label: "Quoted Residual Percentage",
    description: "Residual percentage in decimal form (optional).",
    unit: "%",
    formatRule: "Optional number >= 0",
    validationMessage: "Must be non-negative.",
    defaultValue: "empty",
    modes: ["quote"],
  },
  qir: {
    label: "Quote Lists Interest Rate",
    description: "Whether quote explicitly discloses a rate.",
    unit: "none",
    formatRule: "Boolean",
    validationMessage: "Set true/false.",
    defaultValue: "false",
    modes: ["quote"],
  },
  qri: {
    label: "Quoted Interest Rate",
    description: "Interest rate from provider quote (if shown).",
    unit: "%",
    formatRule: "Optional number >= 0",
    validationMessage: "Must be non-negative.",
    defaultValue: "empty",
    modes: ["quote"],
  },
  quf: {
    label: "Quoted Upfront Fees",
    description: "Aggregate upfront fees from quote (optional).",
    unit: "AUD",
    formatRule: "Optional number >= 0",
    validationMessage: "Must be non-negative.",
    defaultValue: "empty",
    modes: ["quote"],
  },
  qmf: {
    label: "Quoted Monthly Admin Fee",
    description: "Monthly quote admin fee (optional).",
    unit: "AUD/month",
    formatRule: "Optional number >= 0",
    validationMessage: "Must be non-negative.",
    defaultValue: "empty",
    modes: ["quote"],
  },
  qrw: {
    label: "Quote Includes Running Costs",
    description: "Whether quote totals include running costs.",
    unit: "none",
    formatRule: "Boolean",
    validationMessage: "Set true/false.",
    defaultValue: "true",
    modes: ["quote"],
  },
  qfu: {
    label: "Quote Includes Fuel",
    description: "Whether quote totals include fuel/electricity.",
    unit: "none",
    formatRule: "Boolean",
    validationMessage: "Set true/false.",
    defaultValue: "true",
    modes: ["quote"],
  },
  im: {
    label: "Input Style",
    description: "Use your quote for a quick estimate, or enter detailed values.",
    unit: "none",
    formatRule: "quote or detailed",
    validationMessage: "Choose Quote or Detailed mode.",
    defaultValue: "quote",
    modes: ["both"],
  },
  qmp: {
    label: "Quote Monthly Lease Payment",
    description: "Monthly lease payment from your provider quote.",
    unit: "AUD/month",
    formatRule: "Number > 0",
    validationMessage: "Enter quote monthly lease payment greater than 0.",
    defaultValue: "1300",
    modes: ["quote"],
  },
  rat: {
    label: "Annual Running Costs (Total)",
    description: "Single yearly total if you do not have cost breakdowns.",
    unit: "AUD/year",
    formatRule: "Number >= 0",
    validationMessage: "Enter non-negative annual running cost total.",
    defaultValue: "5800",
    modes: ["quote"],
  },
};
